version: "3"
services:

  # MongoDB
  mongo:
    build: docker/mongo
    volumes:
      - ./docker/mongo/mongod.conf:/usr/local/etc/mongod.conf
    expose:
      - 27017
    ports:
      - 27017:27017

  # API
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8080:8080
    links:
      - mongo

  # Scorer
  scorer:
    build:
      context: .
      dockerfile: docker/scorer/Dockerfile
    expose:
      - 8081
    links:
      - mongo
